version: 2
jobs:
  build_1:
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout
      - run:
          name: Install Bundler gem
          command: gem install bundler
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
          # Save test results for timing analysis
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test_results

  build_2:
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - run:
          name: Install Bundler gem
          command: gem install bundler
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
          # Save test results for timing analysis
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_1
      - build_2

